project_id = "lpqkkbtadnqkbathdvzb"

[functions.oauth-meta-callback]
verify_jwt = false

[functions.oauth-facebook-callback]
verify_jwt = false

[functions.oauth-threads-callback]
verify_jwt = false

[functions.oauth-linkedin-callback]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-cloud-webhook]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false