ALTER TABLE videos ADD COLUMN IF NOT EXISTS script_json  JSONB;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS video_format TEXT;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS trim_start   NUMERIC DEFAULT 0;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS trim_end     NUMERIC;
