-- ============================================================
-- Fatia: Auditoria de Feedbacks (Fase 1 -- banco)
-- Data: 2026-05-25
-- ============================================================

-- 1. Expandir CHECK do status pra incluir 'aprovado'
--    novo -> em_analise (pos-auditoria) -> aprovado -> resolvido
--    arquivado em qualquer ponto
ALTER TABLE feedbacks DROP CONSTRAINT IF EXISTS feedbacks_status_check;
ALTER TABLE feedbacks ADD CONSTRAINT feedbacks_status_check
  CHECK (status IN ('novo', 'em_analise', 'aprovado', 'resolvido', 'arquivado'));

-- 2. Tabela de auditorias (1 linha por execucao)
CREATE TABLE IF NOT EXISTS feedback_audits (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at      timestamptz NOT NULL DEFAULT now(),
  created_by      uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  model           text NOT NULL DEFAULT 'claude-opus-4-7',
  feedback_count  int  NOT NULL,
  feedback_ids    uuid[] NOT NULL,
  summary_md      text NOT NULL,
  clusters        jsonb NOT NULL,
  recommendations jsonb NOT NULL,
  nps_snapshot    jsonb,
  status          text NOT NULL DEFAULT 'pending_review'
                  CHECK (status IN ('pending_review', 'acted_on', 'discarded')),
  acted_at        timestamptz,
  duration_ms     int,
  cost_usd        numeric(10,4)
);

CREATE INDEX IF NOT EXISTS feedback_audits_created_at_idx ON feedback_audits (created_at DESC);
CREATE INDEX IF NOT EXISTS feedback_audits_status_idx ON feedback_audits (status);

ALTER TABLE feedback_audits ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "feedback_audits_super_admin_all" ON feedback_audits;
CREATE POLICY "feedback_audits_super_admin_all" ON feedback_audits
  FOR ALL TO authenticated
  USING (is_super_admin())
  WITH CHECK (is_super_admin());

-- 3. Juncao N:N entre auditorias e feedbacks (classificacao granular)
CREATE TABLE IF NOT EXISTS feedback_audit_items (
  audit_id       bigint NOT NULL REFERENCES feedback_audits(id) ON DELETE CASCADE,
  feedback_id    uuid   NOT NULL REFERENCES feedbacks(id)       ON DELETE CASCADE,
  cluster_label  text   NOT NULL,
  classification jsonb  NOT NULL,
  PRIMARY KEY (audit_id, feedback_id)
);

CREATE INDEX IF NOT EXISTS feedback_audit_items_feedback_idx ON feedback_audit_items (feedback_id);
CREATE INDEX IF NOT EXISTS feedback_audit_items_cluster_idx  ON feedback_audit_items (audit_id, cluster_label);

ALTER TABLE feedback_audit_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "feedback_audit_items_super_admin_all" ON feedback_audit_items;
CREATE POLICY "feedback_audit_items_super_admin_all" ON feedback_audit_items
  FOR ALL TO authenticated
  USING (is_super_admin())
  WITH CHECK (is_super_admin());

-- 4. View pra contar quantos feedbacks 'novo' estao disponiveis pra auditar
CREATE OR REPLACE VIEW v_feedbacks_pending_audit AS
SELECT count(*)::int AS pending_count
FROM feedbacks
WHERE status = 'novo';

-- 5. RPC -- aplicar decisao de um cluster (aprova ou descarta em lote)
CREATE OR REPLACE FUNCTION owner_apply_audit_recommendation(
  p_audit_id       bigint,
  p_cluster_label  text,
  p_action         text
) RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_target_status text;
  v_updated       int;
BEGIN
  IF NOT is_super_admin() THEN
    RAISE EXCEPTION 'apenas super admin';
  END IF;

  IF p_action = 'approve' THEN
    v_target_status := 'aprovado';
  ELSIF p_action = 'discard' THEN
    v_target_status := 'arquivado';
  ELSE
    RAISE EXCEPTION 'action invalida (use approve ou discard)';
  END IF;

  UPDATE feedbacks f
     SET status     = v_target_status,
         updated_at = now()
    FROM feedback_audit_items i
   WHERE i.feedback_id   = f.id
     AND i.audit_id      = p_audit_id
     AND i.cluster_label = p_cluster_label;

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RETURN v_updated;
END;
$$;

REVOKE ALL ON FUNCTION owner_apply_audit_recommendation FROM public;
GRANT EXECUTE ON FUNCTION owner_apply_audit_recommendation TO authenticated;

-- 6. RPC -- marcar auditoria como totalmente processada
CREATE OR REPLACE FUNCTION owner_close_audit(p_audit_id bigint, p_status text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_super_admin() THEN
    RAISE EXCEPTION 'apenas super admin';
  END IF;
  IF p_status NOT IN ('acted_on', 'discarded') THEN
    RAISE EXCEPTION 'status invalido';
  END IF;
  UPDATE feedback_audits
     SET status   = p_status,
         acted_at = now()
   WHERE id = p_audit_id;
END;
$$;

REVOKE ALL ON FUNCTION owner_close_audit FROM public;
GRANT EXECUTE ON FUNCTION owner_close_audit TO authenticated;
